function_task:
    alias: 'functional'
    name: 'Basic report functionality test'
    container:
        image: fedora:33
    setup_script:
      - sudo dnf install -y python python-pip
      - pip3 install -r requirements.txt
    main_script: ./bin/sos report --batch
